### ISSUE TITLE
Enhancement: Display last collected value instead of unavailable.

### ISSUE THREAD

**Issue by gchrisak** [DurgNomis-drol/ha_toyota#151]
Hello. Thanks alot for all your efforts!
Would it be possible to display last collected value instead of unavailable on the sensors?
With Toyota connected services being so unstable, every few minutes all sensors show as unavailable.

**Comment by 19fabiom84** [comment]
This is a good idea. Maybe there is possibility to increase the timeout for entities or leave the timeout as customizable field in the config.

**Comment by CM000n** [comment]
To be honest, I don't think that's a good idea. Displaying an "unavailable" is somehow more honest. We don't have the endpoints under control and errors and failures can occur at any time on the part of Toyota or us. The values displayed should also reflect this.
With the new API version, however, the endpoints should be more stable and responsive, so that "unavailable" should no longer be displayed so often 😉

**Comment by fliespl** [comment]
@CM000n are you sure it's stable? https://ss.codeone.pl/ss-2024-04-04-14-59-51-1712235591-uZdS2tkg.png 

I have many issues with it and it's not internet problem since other cloud based sensors work fine. Is there a way to find out root cause why it goes to unavailable state?
