### ISSUE TITLE
Bug: Wrong open/closed status for doors & windows

### ISSUE THREAD

**Issue by CM000n** [DurgNomis-drol/ha_toyota#241]
Since the latest API changes, the open/closed status for windows and doors is no longer displayed correctly.
Although they are closed, an open is displayed for them.
We need to investigate this and possibly adjust our assumptions and models in the mytoyota lib again.

**Comment by desosav** [comment]
For me, sensor status in HA for doors/windows is correct. 
However since v2 i get  sensors for hood, trunk and trunk lock which are always open/unlocked, but not provided by official toyota app.
![Screenshot_20240217-224934_Home Assistant~2](https://github.com/DurgNomis-drol/ha_toyota/assets/47779640/6359196d-a768-494c-b978-16972c9f7097)
![Screenshot_20240217-225015_MyToyota~2](https://github.com/DurgNomis-drol/ha_toyota/assets/47779640/4eb2b7f2-233d-426a-bc2f-67125f4ba439)

**Comment by CM000n** [comment]
Confirmed. This only seems to be a short-term hickup. I'm therefore closing the issue again.

The problem with the trunk sensors that are no longer available (the information for them was available after the initial API change!) is a completely different problem. Feel free to open a separate issue.

Btw. The 'Hood' Sensor ist working correctly for me even if it doesnt show up in the app 😉
